### ISSUE TITLE
Snap is published by unverified account on snapcraft.io

### ISSUE THREAD

**Issue by omhomurlu** [eclipse-theia/theia-ide-snap#5]
The theia-ide snap on [snapcraft.io](https://snapcraft.io/theia-ide) shows the publisher as unverified. If this snap is official, could you please perform the account verification so that the users can see if they are installing the official snap or a snap built by a third party.

**To Reproduce**
1. Go to https://snapcraft.io/theia-ide
2. See that there's no "verified account" check mark next to publisher name

**Expected behavior**
If this is an official snap a green "verified account" check mark should be visible next to the publisher name

**Comment by jfaltermeier** [comment]
See also the following links: 
https://github.com/eclipse-theia/theia/issues/13862#issuecomment-2362133574 
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5021#note_2823488

**Comment by Mailaender** [comment]
@eclipse is now verified. https://forum.snapcraft.io/t/verified-publisher-request-eclipse-foundation/44115
