### ISSUE TITLE
Snap was not updated to 1.56

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-ide-snap#7]
@Mailaender We did not track the update of this, but just noticed it was not updated to 1.56. How can we proceed with this to ensure that the snap build is always updated once a new release is available? For now, I would skip 1.56 and go for 1.57 which is in preview atm.

**Comment by Mailaender** [comment]
I was probably irritated by the missing https://github.com/eclipse-theia/theia-ide/tags Suggest we don't skip a release and do them sequentially because snap has a rollback feature for users.

**Comment by JonasHelming** [comment]
@Mailaender Is there a better way we can notify you? What are you currently watching to know a new release is available?
(@jfaltermeier)

**Comment by Mailaender** [comment]
If you are unable to push to this repository on release in an automated fashion then I can of course pull instead. https://github.com/eclipse-theia/theia-ide-snap/pull/9
